[project]
name = "generatedata"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "confluent-kafka==2.12.2",
    "fastapi==0.123.9",
    "uvicorn==0.38.0",
]
